title: Dr Jessica Witte
theme: jekyll-theme-minimal
logo: /assets/img/headshot.jpeg

#email: "jessica.witte@ed.ac.uk"
#twitter_username: "@jess_witte"
#github_username: "jessicawitte92"
#linkedin_username: "jessicawitte/"


