title: "Dr Jessica Witte"
description: digital humanist | langauge enthusaist | writer & researcher

email: "jessica.witte@ed.ac.uk"
twitter_username: "@jess_witte"
github_username: "jessicawitte92"
linkedin_username: "https://www.linkedin.com/in/jessicawitte/"


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
  - scope:
      path: ""
      type: post
    values:
      tags: Other
