title: Dr Jessica Witte
theme: jekyll-theme-minimal
logo: /assets/img/headshot.jpeg

social_links: true  # If true show social links
rss: true # For add icon to link feed.xml
github: "jessicawitte92"
linkedin: "jessicawitte"
twitter: @jess_witte




